name: Deploy Docker Container

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t simple-reactjs-app .

      # Log in to Docker Hub or a registry
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push image to registry
      - name: Push Docker Image
        run: docker tag simple-reactjs-app mydockerusername/simple-reactjs-app:latest
      - name: Push image to DockerHub
        run: docker push mydockerusername/simple-reactjs-app:latest

      # SSH into EC2 and pull & run the container
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker pull mydockerusername/simple-reactjs-app:latest
            docker stop react-app || true
            docker rm react-app || true
            docker run -d --name simple-reactjs-app -p 80:80 mydockerusername/simple-reactjs-app:latest
