# .github/workflows/deploy-ec2.yml
name: Deploy React App on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: ubuntu-latest

    steps:
    - name: Deploy on EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          # Install Docker if not installed
          if ! command -v docker &> /dev/null
          then
            echo "Docker not found. Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo usermod -aG docker $(whoami)
            sudo systemctl enable docker
            sudo systemctl start docker
          else
            echo "Docker is already installed"
          fi

          # Pull the Docker image
          docker pull ${{ secrets.DOCKER_USERNAME }}/simple-reactjs-app:latest

          # Stop and remove any existing container
          sudo docker stop simple-reactjs-app || true
          sudo docker rm simple-reactjs-app || true

          # Run the new container (on port 80)
          sudo docker run -d --name simple-reactjs-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/simple-reactjs-app:latest
