name: Deploy Docker Container

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Build the Docker image with the correct tag
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-reactjs-app:latest .

      # List all Docker images to verify the image was built correctly
      - name: List Docker Images
        run: docker images

      # Log in to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to DockerHub
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-reactjs-app:latest

      # Deploy on EC2 instance via SSH
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/simple-reactjs-app:latest
            docker stop react-app || true
            docker rm react-app || true
            docker run -d --name simple-reactjs-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/simple-reactjs-app:latest
